name: 'Get environments'
description: 'Retrieve environment for current repository'
outputs:
  names: ${{ toJson(fromJson(steps.get_env.outputs.data).environments.*.name) }}  
runs:   
  using: composite
  steps:
    - name: Get environments
      shell: bash
      uses: octokit/request-action@v2.3.0
      id: get_env
      with:
        route: GET /repos/${{ github.repository }}/environments?per_page=100 # If we ever have >100 deployments, we'll need to paginate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}