on:
  workflow_call:
    inputs:
      java-version:
        type: string
        description: "[Version Java à être utiliser](https://github.com/actions/setup-java#supported-version-syntax)"
        required: true
        default: ""
      distribution:
        type: string
        description: "[Distribution Java](https://github.com/actions/setup-java#supported-distributions)"
        required: true
        default: ""
      architecture:
        type: choice
        description: "Architecture cible (x86, x64, armv7, aarch64, ppc64le)"
        options:
        - x86
        - x64
        - armv7
        - aarch64
        - ppc64le
        default: "x86"

env:
  MVNCMD: ./mvnw -B 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ github.event.inputs.java-version }}
        distribution: ${{ github.event.inputs.distribution }}
        architecture: ${{ github.event.inputs.architecture }}
        cache: maven

    - name: Detect maven wrapper
      run: |
        if [ -f ${{ github.workspace }}/mvnw ]; then
          git chmod +x ${{ github.workspace }}/mvnw
        else
          echo "Assurez-vous d'installer le wrapper maven" && exit 1
        fi
      shell: bash

    - name: Prepare release
      run: |
        git clean -f -d -x
        $MVNCMD -P allmodules clean release:clean release:prepare -DpushChanges=false

    - name: Perform release
      run: |
        $MVNCMD release:perform -DlocalCheckout=true -DdeployAtEnd=true "-Dgoals=clean install package source:jar javadoc:jar deploy"

    - name: Commit & Push new version
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        message: '[github_action][skip ci] Incrément de la version à publier à ${{ steps.version_rc.outputs.version }}'
  
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1