name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'actions/*'
      - 'workflows/*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to release the next version
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Bump Version
        id: version
        uses: paulhatch/semantic-version@v5.3.0

      - name: Build new version
        if: steps.version.outputs.changed
        uses: ./.github/actions/build-new-version
        with:
          version: ${{ steps.version.outputs.version }}

      - name: Release new Version
        if: steps.version.outputs.changed
        uses: ./.github/actions/release-new-version
        with:
          version: ${{ steps.version.outputs.version }}