name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'actions/*'
      - 'workflows/*'

jobs:
  test-increment-semver-job:
    runs-on: ubuntu-latest
    name: A job to release the next version
    permissions:
      contents: write
    steps:
#      Note Checkout is required for ${GITHUB_WORKSPACE} to be not empty
      - name: Checkout
        uses: actions/checkout@v1

      - name: Bump Version
        id: version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          change_path: 'src'
          version_format: '${major}.${minor}.${patch}'

      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v2

      - name: Write next release candidate version
        if: ${{ steps.version.outputs.c }}
        run: |
          for d in actions/*/; {
            pushd $d;
            if [ -f "package.json" ]; then
              tmp=$(mktemp);
              jq '.version = "${{ steps.version.outputs.version }}"' package.json > "$tmp" && mv "$tmp" package.json;
            fi
            popd;
          }
        shell: bash
  
      - name: Commit & Push new version
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}"
          message: '[github_action][skip ci] update version to ${{ steps.version.outputs.version }} in package.json'
  
      - name: Create Git Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.version_tag }}
    
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}