name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "actions/*"
      - "workflows/*"

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to build javascript actions and release the next version
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Bump Version
        id: version
        uses: paulhatch/semantic-version@v5.3.0

      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0
        with:
          jq-version: 1.7
          required: true

      - name: Write new version to package.json
        run: |
          for d in actions/*/; {
            pushd $d;
            if [ -f "package.json" ]; then
              tmp=$(mktemp);
              jq '.version = "${{ github.action.inputs.version }}"' package.json > "$tmp" && mv "$tmp" package.json;
            fi
            popd;
          }
        shell: bash

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Build new version package
        run: |
          for d in actions/*/; {
            pushd $d;
            if [ -f "package.json" ]; then
              npm install;
              npm run all;
            fi
            popd;
          }
        shell: bash

      - name: Commit & Push new version and new packages
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}"
          message: "[github_action][skip ci] update version to ${{ steps.version.outputs.version }}"

      - name: Create Git Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.version }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
